version: "3.7"
services:
  rabbitmq-message-broker:
    container_name: "rabbitmq-message-broker"
    image: rabbitmq:3-management
    volumes:
    - ./definitions.json:/opt/definitions.json:ro
    - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    name: rabbitmq-network