package rs.vakcinacija.imunizacija.interesovanje.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import rs.vakcinacija.imunizacija.interesovanje.model.Interesovanje;
import rs.vakcinacija.zajednicko.data.repository.ExistRepository;
import rs.vakcinacija.zajednicko.metadata.repository.FusekiRepository;
import rs.vakcinacija.zajednicko.service.DocumentService;

import java.util.List;
import java.util.UUID;

@Service
public class InteresovanjeService extends DocumentService<Interesovanje> {
    @Autowired
    public InteresovanjeService(ExistRepository<Interesovanje> existRepository,
                                FusekiRepository<Interesovanje> fusekiRepository) {
        super(existRepository, fusekiRepository);
    }

    public List<Interesovanje> getAllForUser(String email) throws Exception {
        return existRepository.read((doc) -> doc.getLicneInformacije().getKontakt()
                .getEmail().getValue().equals(email));
    }

    protected void insertRDFMetadata(Interesovanje interesovanje) {
        var datum = interesovanje.getDatum();
        datum.setProperty(PROP_DATUM);
        datum.setDatatype(T_DATE);

        var mesto = interesovanje.getOdabranaLokacijaPrimanjaVakcine();
        mesto.setProperty(PROP_MESTO);
        mesto.setDatatype(T_STRING);

        var autogeneratedId = UUID.randomUUID();
        interesovanje.setId(autogeneratedId);

        var podnosilacZahteva = interesovanje.getLicneInformacije();

        String podnosilacUrl = RDF_PACIJENT_BASE + interesovanje.getLicneInformacije().getKontakt()
                .getEmail().getValue();

        interesovanje.setVocab(VOCAB);
        interesovanje.setAbout(RDF_INTERESOVANJE_BASE + autogeneratedId);
        interesovanje.setRel(PROP_PODNESEN_OD);
        interesovanje.setTypeof(T_INTERESOVANJE);
        interesovanje.setHref(podnosilacUrl);

        podnosilacZahteva.setVocab(VOCAB);
        podnosilacZahteva.setAbout(podnosilacUrl);

        var jmbg = podnosilacZahteva.getJmbg();
        jmbg.setProperty(PROP_JMBG);
        jmbg.setDatatype(T_STRING);

        var ime = interesovanje.getLicneInformacije().getImePrezime().getIme();
        ime.setProperty(PROP_IME);
        ime.setDatatype(T_STRING);

        var prezime = interesovanje.getLicneInformacije().getImePrezime().getPrezime();
        prezime.setProperty(PROP_PREZIME);
        prezime.setDatatype(T_STRING);

        var davalac = interesovanje.getLicneInformacije().getDavalacKrvi();
        davalac.setProperty(PROP_DAVALAC_KRVI);
        davalac.setDatatype(T_BOOLEAN);

        var brojFiksnog = interesovanje.getLicneInformacije().getKontakt().getBrojFiksnog();
        brojFiksnog.setProperty(PROP_BROJ_FIKSNOG);
        brojFiksnog.setDatatype(T_STRING);

        var brojMobilnog = interesovanje.getLicneInformacije().getKontakt().getBrojMobilnog();
        brojMobilnog.setProperty(PROP_BROJ_MOBILNOG);
        brojMobilnog.setDatatype(T_STRING);

        var email = interesovanje.getLicneInformacije().getKontakt().getEmail();
        email.setProperty(PROP_EMAIL);
        email.setDatatype(T_STRING);
    }
}
