version: "3.7"
services:
  email-service:
    container_name: "email-service-api"
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      API_PORT: 8088
      RABBITMQ_HOST: rabbitmq-message-broker
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    ports:
      - "8088:8088"
    networks:
      - email-service-network
      - rabbitmq-network

networks:
  email-service-network:
    name: email-service-network
  rabbitmq-network:
    external:
      name: rabbitmq-network