version: "3.7"
services:
  imunizacija-xml-db:
    container_name: "imunizacija-xml-exist-database"
    image: existdb/existdb:4.6.1
    ports:
      - "8083:8080"
    networks:
      - imunizacija-service-network
  imunizacija-rdf-db:
    container_name: "imunizacija-rdf-database"
    image: stain/jena-fuseki:3.14.0
    ports:
      - "8085:3030"
    environment:
      - ADMIN_PASSWORD=password
      - FUSEKI_DATASET_1=VakcinacijaDataset
    networks:
      - imunizacija-service-network

# TODO: Commented out for development and debug purposes
#  imunizacija-service:
#    container_name: "imunizacija-service-api"
#    build:
#      context: .
#      dockerfile: .docker/Dockerfile
#    environment:
#      API_PORT: 8081
#      EXIST_DB_USER: admin
#      EXIST_DB_PASSWORD:
#      EXIST_DB_HOST: imunizacija-xml-db
#      EXIST_DB_PORT: 8080
#    ports:
#      - "8081:8081"
#    networks:
#      - imunizacija-service-network

networks:
  imunizacija-service-network:
    name: imunizacija-service-network